# Generated by Django 4.0.5 on 2022-12-12 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_alter_ingredientcreatemodel_name'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecreatemodel',
            name='ingredients',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredientcreatemodel'),
            preserve_default=False,
        ),
    ]
