# Generated by Django 4.0.5 on 2022-12-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipecreatemodel_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecreatemodel',
            options={'verbose_name': 'Add Recipe'},
        ),
    ]
