# Generated by Django 4.0.5 on 2022-12-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipecreatemodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecreatemodel',
            name='recipe_picture',
            field=models.ImageField(blank=True, default='media_files/NoPictureForRecipe.jpg', null=True, upload_to='recipes'),
        ),
    ]
