# Generated by Django 4.0.5 on 2022-12-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipecreatemodel_recipe_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecreatemodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
