# Generated by Django 4.0.5 on 2022-12-12 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredientaddtofridgemodel_ingredientcreatemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientaddtofridgemodel',
            name='ingredients',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredientcreatemodel'),
            preserve_default=False,
        ),
    ]
