# Generated by Django 4.0.5 on 2022-12-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_ingredientaddtofridgemodel_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientcreatemodel',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
