# Generated by Django 4.0.5 on 2022-12-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_alter_ingredientcreatemodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientcreatemodel',
            options={'verbose_name': 'Add Ingredient'},
        ),
        migrations.AlterField(
            model_name='ingredientcreatemodel',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
