# Generated by Django 4.0.5 on 2022-12-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0005_alter_ingredientcreatemodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientaddtofridgemodel',
            name='amount',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
