# Generated by Django 4.0.5 on 2022-12-17 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_remove_ingredientaddtofridgemodel_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientaddtofridgemodel',
            name='ingredients',
            field=models.OneToOneField(error_messages={'unique_check': 'You already have this ingredient in your fridge.'}, on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredientcreatemodel'),
        ),
    ]
